# Generated by Django 4.2.5 on 2023-11-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mision_Animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalito',
            name='descripcion',
            field=models.CharField(max_length=400),
        ),
    ]
