# Generated by Django 4.2.5 on 2023-11-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('nombre_del_evento', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('lugar', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
